rc("text", usetex=true)
rc("font", family="serif")

# Generate plots of final designs
figure(figsize=(7, 3))
# subplot(131)
# title("ADMM with simple initialization")
# imshow(reshape(primal_ab_initio["all_design"][ab_initio_stop_idx,:], N, N), cmap="Purples")
subplot(121)
title("Suggested initial design")
imshow(reshape(dual_problem["theta_init"], N, N), cmap="Purples")
axis("off")
subplot(122)
title("Locally-optimized design")
imshow(reshape(primal_dual_init["all_design"][dual_init_stop_idx,:], N, N), cmap="Purples")
axis("off")
tight_layout(w_pad=-10)
savefig("resonator_theta_initialization_comparison_toc.pdf", bbox_inches="tight")
# close()